//! This is an automatically generated file; do not edit.
//! Generated by gen_ccompat_tests.c on Jun 23 2024 07:28:17

#[test]
fn test_ioctl_ccompat() {
    assert_eq!(super::IOC_DIRBITS, 2);
    assert_eq!(super::IOC_SIZEBITS, 14);
}
