#include <linux/ioctl.h>
#include <linux/gpio.h>
#include <stddef.h>
#include <stdio.h>

int ioctl_ccompat_test();
int gpio_ioctl_ccompat_test();

int main() {
    if (gpio_ioctl_ccompat_test() != 0) {
        return 1;
    }
}

#define EQ_CHECK(name) fprintf(fp, "    assert_eq!(super::%s, 0x%x);\n", #name, name)
#define EQ_CHECK2(rname, cname) fprintf(fp, "    assert_eq!(super::%s, %u);\n", #rname, cname)
#define SIZE_CHECK(rname, cname) fprintf(fp, "    assert_eq!(size_of::<super::%s>(), %zu);\n", #rname, sizeof(struct cname))
#define OFFSET_CHECK(rname, cname, field) fprintf(fp, "    assert_eq!(offset_of!(super::%s, %s), %zu);\n", #rname, #field, offsetof(struct cname, field))
#define OFFSET_CHECK_ANON_UNION(rparent, rparent_field, rname, cname, field) fprintf(fp, "    assert_eq!(offset_of!(super::%s, %s) + offset_of!(super::%s, %s), %zu);\n", #rparent, #rparent_field, #rname, #field, offsetof(struct cname, field))

int gpio_ioctl_ccompat_test() {
    FILE *fp = fopen("src/gpio_ioctl/ccompat_tests.rs", "w");
    if (fp == NULL) {
        perror("gpio_ioctl_ccompat_test.rsinc");
        return 1;
    }

    fprintf(fp, "//! This is an automatically generated file; do not edit.\n");
    fprintf(fp, "//! Generated by gen_ccompat_tests.c on %s %s\n", __DATE__, __TIME__);
    fprintf(fp, "use std::mem::{offset_of, size_of};\n");
    fprintf(fp, "\n");
    fprintf(fp, "#[test]\n");
    fprintf(fp, "fn test_gpio_ioctl_ccompat() {\n");
    EQ_CHECK(GPIO_GET_CHIPINFO_IOCTL);
    EQ_CHECK(GPIO_GET_LINEINFO_UNWATCH_IOCTL);
    EQ_CHECK(GPIO_V2_GET_LINEINFO_IOCTL);
    // EQ_CHECK(GPIO_V2_GET_LINEINFO_WATCH_IOCTL);
    // EQ_CHECK(GPIO_V2_GET_LINE_IOCTL);
    // EQ_CHECK(GPIO_V2_LINE_SET_CONFIG_IOCTL);
    // EQ_CHECK(GPIO_V2_LINE_SET_VALUES_IOCTL);
    EQ_CHECK(GPIO_V2_LINE_ATTR_ID_FLAGS);
    EQ_CHECK(GPIO_V2_LINE_ATTR_ID_OUTPUT_VALUES);
    EQ_CHECK(GPIO_V2_LINE_ATTR_ID_DEBOUNCE);
    SIZE_CHECK(RawGpioChipInfo, gpiochip_info);
    SIZE_CHECK(RawGpioV2LineAttr, gpio_v2_line_attribute);
    SIZE_CHECK(RawGpioV2LineInfo, gpio_v2_line_info);
    // SIZE_CHECK(RawGpioV2LineValues, gpio_v2_line_values);
    OFFSET_CHECK(RawGpioV2LineAttr, gpio_v2_line_attribute, id);
    OFFSET_CHECK(RawGpioV2LineAttr, gpio_v2_line_attribute, padding);
    OFFSET_CHECK_ANON_UNION(RawGpioV2LineAttr, data, RawGpioV2LineAttrValue, gpio_v2_line_attribute, flags);
    OFFSET_CHECK_ANON_UNION(RawGpioV2LineAttr, data, RawGpioV2LineAttrValue, gpio_v2_line_attribute, values);
    OFFSET_CHECK_ANON_UNION(RawGpioV2LineAttr, data, RawGpioV2LineAttrValue, gpio_v2_line_attribute, debounce_period_us);
    OFFSET_CHECK(RawGpioV2LineInfo, gpio_v2_line_info, name);
    OFFSET_CHECK(RawGpioV2LineInfo, gpio_v2_line_info, consumer);
    OFFSET_CHECK(RawGpioV2LineInfo, gpio_v2_line_info, offset);
    OFFSET_CHECK(RawGpioV2LineInfo, gpio_v2_line_info, num_attrs);
    OFFSET_CHECK(RawGpioV2LineInfo, gpio_v2_line_info, flags);
    OFFSET_CHECK(RawGpioV2LineInfo, gpio_v2_line_info, attrs);
    OFFSET_CHECK(RawGpioV2LineInfo, gpio_v2_line_info, padding);
    fprintf(fp, "}");
    fclose(fp);    
}